### ISSUE TITLE
Mark Cross Country

### ISSUE THREAD

**Issue by KatieJia** [KatieJia/ICS3U_2014#1]
Please mark my cross country assignment

**Comment by kevindeslauriers** [comment]
Excellent Work - very well written, it was organised and met all requirements.

![day 5 - rubric cross country assignment - katie j_page_1](https://cloud.githubusercontent.com/assets/739858/5172311/b1d9027c-73ec-11e4-8202-243a35ceb10e.jpg)
![day 5 - rubric cross country assignment - katie j_page_2](https://cloud.githubusercontent.com/assets/739858/5172312/b1da3d72-73ec-11e4-8bde-bda40198bb25.jpg)
