### ISSUE TITLE
please mark this hell project

### ISSUE THREAD

**Issue by KatieJia** [KatieJia/ICS3U_2014#2]
hated this

**Comment by kevindeslauriers** [comment]
![image](https://cloud.githubusercontent.com/assets/739858/6340883/22e869de-bb92-11e4-82e7-fead135cd8fc.png)

Good work - although some of the game play needed to be tested abit more.  As you will see by the image I lost a hand even though the dealer busted.

Also it appears that the locale is not being used when we display the $$.

K 9/10
I 12/15
C 10/10
A 9.5/10

89%
